# Site settings
title: BioStandards
email: yassinesouilmi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  testbed for case study publication
url: http://yassines.github.io  # the base hostname & protocol for your site
twitter_username: The_Smiao
github_username:  yassineS
encoding: utf-8

# Build settings
# markdown: redcarpet
# highlighter: pygments
# extensions: [tables fenced_code_blocks]

exclude: [vendor]
kramdown:
   input: GFM
gems:
  - jekyll-sitemap
