name: BioStandards
description: Code, data and standards
meta_description: "Bioinformatics and data code, thoughts, and standards"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://yassines.github.io/'
google_analytics: 'UA-68129481-1'
disqus: true
disqus_shortname: 'biostandards'

# Details for the RSS feed generator
url:            'http://yassines.github.io/'
author:         'Yassine Souilmi'
authorTwitter:  'The_Smiao'

permalink:       /:year/:month/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
